# Deep Learnig 第4回

# ニューラルネットワーク2

![ニューラルネットワーク](images/neural-network-2/neural-network3.svg)

## 恒等関数とソフトマックス関数

### 恒等関数
入力に対して同じ出力を返す関数

### ソフトマックス関数
出力の和を1にして返してくれる関数  
出力を確率として扱う事ができる

![ニューラルネットワーク](images/neural-network-2/sigma.svg)

$${ y }_{ k }=\frac { exp({ a }_{ k }) }{ \sum _{ i=1 }^{ n }{ exp({ a }_{ i }) }  } $$

ただし、これではexpの値が大きくなりすぎる。

上記の式はaをa+Cとしても成り立つので以下のように書ける。

$${ y }_{ k }=\frac { exp({ a }_{ k }+C) }{ \sum _{ i=1 }^{ n }{ exp({ a }_{ i }+C) }  } $$

入力のなかで最も大きな値を引いてやれば計算に耐えうる値になる

In [27]:
import numpy as np

In [6]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a

    return y

In [11]:
a = np.array([1010, 1000, 990])

In [12]:
np.exp(a) / np.sum(np.exp(a))

/home/ubuntu/.pyenv/versions/miniconda3-4.1.11/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: overflow encountered in exp
  if __name__ == '__main__':
/home/ubuntu/.pyenv/versions/miniconda3-4.1.11/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([ nan,  nan,  nan])

In [10]:
softmax(a)

array([  9.99954600e-01,   4.53978686e-05,   2.06106005e-09])

In [13]:
a = np.array([0.3, 2.9, 4.0])

In [14]:
softmax(a)

array([ 0.01821127,  0.24519181,  0.73659691])

## MNIST
機械学習の研究などに用いられる手書き数字のデータセット

https://www.google.co.jp/search?q=MNIST&safe=off&espv=2&biw=1300&bih=733&source=lnms&tbm=isch&sa=X&ved=0ahUKEwicto6mqfXRAhVFa7wKHdVRBAQQ_AUIBigB

MNISTの手書き数字の分類をしたい

![ニューラルネットワーク](images/neural-network-2/output-neuron.svg)

### MNISTデータの読み込み

In [18]:
import sys, os
sys.path.append(os.pardir)
from dataset.mnist import load_mnist # https://github.com/oreilly-japan/deep-learning-from-scratch/blob/master/dataset/mnist.py

(x_train, t_train), (x_test, t_test) = load_mnist(normalize=True, flatten=True, one_hot_label=False)

Done
Done
Done
Done
Converting train-images-idx3-ubyte.gz to NumPy Array ...
Done
Converting train-labels-idx1-ubyte.gz to NumPy Array ...
Done
Converting t10k-images-idx3-ubyte.gz to NumPy Array ...
Done
Converting t10k-labels-idx1-ubyte.gz to NumPy Array ...
Done
Creating pickle file ...
Done!


In [19]:
print(x_train.shape)

(60000, 784)


## ニューラルネットワーク実装

In [21]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# https://github.com/oreilly-japan/deep-learning-from-scratch/blob/master/ch03/sigmoid.py

In [30]:
import pickle

In [31]:
def get_data():
    (x_train, t_train), (x_test, t_test) = load_mnist(normalize=True, flatten=True, one_hot_label=False)
    return x_test, t_test


def init_network():
    with open("sample_weight.pkl", 'rb') as f:
        network = pickle.load(f)
    return network


def predict(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = softmax(a3)

    return y


x, t = get_data()
network = init_network()
accuracy_cnt = 0
for i in range(len(x)):
    y = predict(network, x[i])
    p= np.argmax(y) # 最も確率の高い要素のインデックスを取得
    if p == t[i]:
        accuracy_cnt += 1

print("Accuracy:" + str(float(accuracy_cnt) / len(x)))

# https://github.com/oreilly-japan/deep-learning-from-scratch/blob/master/ch03/neuralnet_mnist.py

Accuracy:0.9352


$${ a }_{ 1 }={ w }_{ 11 }{ x }_{ 1 }+{ w }_{ 12 }{ x }_{ 2 }+{ b }_{ 1 }$$

$$A=XW+B$$

$$A=\begin{pmatrix} { a }_{ 1 } & { a }_{ 2 } & { a }_{ 3 } \end{pmatrix}$$

$$X=\begin{pmatrix} { x }_{ 1 } & { x }_{ 2 } \end{pmatrix}$$

$$B=\begin{pmatrix} b_{ 1 } & b_{ 2 } & b_{ 3 } \end{pmatrix}$$

$$W=\begin{pmatrix} w_{ 11 } & w_{ 21 } & w_{ 31 } \\ w_{ 12 } & w_{ 22 } & w_{ 32 } \end{pmatrix}$$

![ニューラルネットワーク](images/neural-network-2/neural-network3.svg)